language: php
php:
  - '5.6'

install:
  - composer install --no-interaction

before_script: phpenv config-add .build/php.ini

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
