language: php
php:
  - '5.6'

install:
  - composer install --no-interaction


script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - composer require satooshi/php-coveralls dev-master
  - vendor/bin/coveralls -v --exclude-no-stmt